language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /v(\d+)\.(\d+)\.(\d+)/
matrix:
  allow_failures:
  - julia: nightly
codecov: true
