name: CompatHelper
on:
  schedule:
    - cron: '0 1 * * *'
  issues:
    types: [opened, reopened]
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(name = "CompatHelper", url = "https://github.com/bcbi/CompatHelper.jl.git"))'
      - name: CompatHelper.main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_DEBUG: CompatHelper
        run: julia -e 'using CompatHelper; CompatHelper.main()'
